### ISSUE TITLE
summarize_one() function output _VarImp.csv always has the 'test' prefix

### ISSUE THREAD

**Issue by toujames** [kforthman/caretStack#6]
When invoking the summarize_one() function, the output filename for _VarImp.csv is always 'test_VarImp.csv'. It doesn't use the 'rdata_prefix' parameter.

**Comment by kforthman** [comment]
It seems the prefix is saved in the '.results.RData' file. When it is loaded in the first line of the `summarize_one()` function, the `rdata_prefix` variable in that file overwrites the argument to the function.

Thank you for calling my attention to this bug! This should be fixed in the newest update.
